<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>48contingency</AssemblyName>
    <RootNamespace>OpaliteMoonMod</RootNamespace>
  </PropertyGroup>
  
  <PropertyGroup>
    <!-- Build dependency paths -->
    <GameManaged>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed</GameManaged>
    <BepinEx>C:\Program Files (x86)\Steam\steamapps\content\app_1966720\v81 hotfix 5\BepInEx</BepinEx>
    <!-- (dont change) -->
    <BepInExPlugins>$(BepinEx)\plugins\FlintChips-48_Contingency</BepInExPlugins>
    <UnityModPlugins>$(MSBuildProjectDirectory)\LC Mod Testing\Assets\LethalCompany\Mods\plugins\OpaliteMod</UnityModPlugins>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="TeamXiaolan.DawnLib" Version="0.9.25" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.9" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepinEx)\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="JLL">
      <HintPath>$(BepinEx)\plugins\JacobG5-JLL\JLL\JLL.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepinEx)\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManaged)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    
    <Reference Include="UnityEngine">
      <HintPath>$(GameManaged)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManaged)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>$(GameManaged)\Unity.Netcode.Runtime.dll</HintPath>
    </Reference>
    <!-- add more .dlls here as needed -->
  </ItemGroup>
  
  <!-- build stuffs -->

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ApparatusDockHandler.cs" />
    <Compile Include="ContingencyWaterTrigger.cs" />
    <Compile Include="ControlRoomManager.cs" />
    <Compile Include="ControlRoomPlayerManager.cs" />
    <Compile Include="ControlRoomSteamValve.cs" />
    <Compile Include="ControlRoomTeleport.cs" />
    <Compile Include="FloodWaterZone.cs" />
    <Compile Include="KyividManager.cs" />
    <Compile Include="OpaliteMoonPlugin.cs" />
    <Compile Include="RandomizedDropSoundObject.cs" />
    <Compile Include="StartDelugeLever.cs" />
    <!-- include more if needed, this is so the csproj ignores everything in the unity project -->
  </ItemGroup>

  <Target Name="NetcodePatch" AfterTargets="PostBuildEvent">
    <Exec Command="netcode-patch -uv 2022.3.62 -nv 1.12.2 -tv 1.0.0 &quot;$(TargetPath)&quot; @(ReferencePathWithRefAssemblies->'&quot;%(Identity)&quot;', ' ')"/>
  </Target>
  
  <Target Name="CopyToPlugins" AfterTargets="Build">
    <MakeDir Directories="$(BepInExPlugins);$(UnityModPlugins)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BepInExPlugins)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(UnityModPlugins)" SkipUnchangedFiles="true" />
    <Message Importance="high" Text="Copied $(TargetPath) -> $(BepInExPlugins)" />
    <Message Importance="high" Text="Copied $(TargetPath) -> $(UnityModPlugins)" />
  </Target>

  <Target Name="CopyAssetFiles" AfterTargets="Build">
    <ItemGroup>
      <BundleFiles Include="$(UnityModPlugins)\AssetBundles\AssetBundles" />
      <BundleFiles Include="$(UnityModPlugins)\AssetBundles\opaliteScene" />
      <BundleFiles Include="$(UnityModPlugins)\AssetBundles\opilate_moon_definition" />
      <BundleFiles Include="$(UnityModPlugins)\AssetBundles\soppingzeddogdefinition" />
      <DuskMod Include="$(UnityModPlugins)\AssetBundles\opalitemainassets.duskmod" />
    </ItemGroup>
    <Copy
            SourceFiles="@(DuskMod)"
            DestinationFolder="$(BepInExPlugins)"
            SkipUnchangedFiles="true" />
    <Copy
          SourceFiles="@(BundleFiles)"
          DestinationFolder="$(BepInExPlugins)\Assets"
          SkipUnchangedFiles="true" />
    <Message Importance="high" Text="Copied @(BundleFiles) -> $(BepInExPlugins)\plugins\Assets" />
    <Message Importance="high" Text="Copied @(DuskMod) -> $(BepInExPlugins)\plugins" />
    </Target>
</Project>